# Generated by Django 5.0.2 on 2024-09-23 13:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nirbhik_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLocationRecordTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('longitude', models.CharField(max_length=50)),
                ('latitude', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
